### ISSUE TITLE
Only downloads statistics for 420 most recent posts

### ISSUE THREAD

**Issue by raffg** [illonage/illonage.github.io#1]
I have 1000+ posts on my Instagram but this web data connector only downloads the 420 most recent ones. Is that limit imposed by Instagram? Can it be increased? (by the way, thank you for building this! It's great otherwise!)

**Comment by illonage** [comment]
Hi Greg, 
What is your email?

**Comment by raffg** [comment]
Hi Geraldine, it's greg.rafferty at gmail. I actually got it all figured out in September and got the permissions I needed from Instagram, so everything is working perfectly! Go ahead an email me anyways if you'd like, but I did manage to get my own WDC working. Thanks!
