### ISSUE TITLE
Instagram web connector

### ISSUE THREAD

**Issue by Jomondo** [illonage/illonage.github.io#2]
Dear Geraldine (@illonage),

I'm trying to get insights from Instagram and I am using your Instagram Connector, that is amazing!

It's working very fine, but it does not have video views as a metric. I'm not a developer, so I've no idea if it is simple to add this metrics in the connector. If possible, could you please help me on this?

Many thanks in advance!!!

Giorgio

**Comment by illonage** [comment]
Hi Giorgio,

Thank you for your feedback.

I used Instagram's API to develop this WDC and unfortunately, Instagram is not giving this information, the number of views via their API.

**Comment by Jomondo** [comment]
Hi Geraldine,

Thank a lot for your reply. 

Do you think they will provide this information in the future, or there is another way to get it?

Thanks a lot in advance!

Giorgio

**Comment by Jomondo** [comment]
Hello Geraldine (@illonage),

Should I close the ticket or there is still a hope on resolving it?

Thanks a lot,

Giorgio

**Comment by awollam** [comment]
Hi Geraldine,
Thank you for your Instagram Web connector for Tableau which is amazing. I noticed that the download data allows only one year range. Is there any way we could get all the data associated with the user account (from the first post to last post)? 
Thanks!

Aye

**Comment by illonage** [comment]
Hi Aye,

Yes, I set a limitation in the code. I explained to Greg on the community how to update it: https://community.tableau.com/thread/178865?start=75&tstart=0
