### ISSUE TITLE
Error when connecting to Instagram

### ISSUE THREAD

**Issue by awollam** [illonage/illonage.github.io#3]
Hi,
When connecting to the Instagram web data connector, I received the following error:
TypeError: undefined is not an object (evaluating 'data.data[0]') file: https://illonage.github.io/instagram.js line: 265
The data did not download. 
Thanks!
Aye

**Comment by illonage** [comment]
Hi Aye,
 Yes, Instagram changed their API. I updated the WDC, it should work now but only for your account. Lets me know if you still have an issue

**Comment by awollam** [comment]
Thank you so much Geraldine!
